In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("C:\\Users\\Sawpanil\\Downloads\\archive (4)\\Spotify Most Streamed Songs.csv")

In [5]:
data=pd.DataFrame(data)

In [6]:
data.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,B,Major,80,89,83,31,0,8,4,Not Found
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,C#,Major,71,61,74,7,0,10,4,https://i.scdn.co/image/ab67616d0000b2730656d5...
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,F,Major,51,32,53,17,0,31,6,https://i.scdn.co/image/ab67616d0000b273e85259...
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,A,Major,55,58,72,11,0,11,15,https://i.scdn.co/image/ab67616d0000b273e787cf...
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,A,Minor,65,23,80,14,63,11,6,https://i.scdn.co/image/ab67616d0000b273ab5c9c...

In [7]:
print(data)

                              track_name      artist(s)_name  artist_count  \
0    Seven (feat. Latto) (Explicit Ver.)    Latto, Jung Kook             2
1                                   LALA         Myke Towers             1
2                                vampire      Olivia Rodrigo             1
3                           Cruel Summer        Taylor Swift             1
4                         WHERE SHE GOES           Bad Bunny             1
..                                   ...                 ...           ...
948                         My Mind & Me        Selena Gomez             1
949            Bigger Than The Whole Sky        Taylor Swift             1
950                 A Veces (feat. Feid)  Feid, Paulo Londra             2
951                        En La De Ella  Feid, Sech, Jhayco             3
952                                Alone           Burna Boy             1

     released_year  released_month  released_day  in_spotify_playlists  \
0             2023               7            14                   553
1             2023               3            23                  1474
2             2023               6            30                  1397
3             2019               8            23                  7858
4             2023               5            18                  3133
..             ...             ...           ...                   ...
948           2022              11             3                   953
949           2022              10            21                  1180
950           2022              11             3                   573
951           2022              10            20                  1320
952           2022              11             4                   782

     in_spotify_charts    streams  in_apple_playlists  ...  key   mode  \
0                  147  141381703                  43  ...    B  Major
1                   48  133716286                  48  ...   C#  Major
2                  113  140003974                  94  ...    F  Major
3                  100  800840817                 116  ...    A  Major
4                   50  303236322                  84  ...    A  Minor
..                 ...        ...                 ...  ...  ...    ...
948                  0   91473363                  61  ...    A  Major
949                  0  121871870                   4  ...   F#  Major
950                  0   73513683                   2  ...   C#  Major
951                  0  133895612                  29  ...   C#  Major
952                  2   96007391                  27  ...    E  Minor

     danceability_% valence_%  energy_% acousticness_% instrumentalness_%  \
0                80        89        83             31                  0
1                71        61        74              7                  0
2                51        32        53             17                  0
3                55        58        72             11                  0
4                65        23        80             14                 63
..              ...       ...       ...            ...                ...
948              60        24        39             57                  0
949              42         7        24             83                  1
950              80        81        67              4                  0
951              82        67        77              8                  0
952              61        32        67             15                  0

     liveness_%  speechiness_%  \
0             8              4
1            10              4
2            31              6
3            11             15
4            11              6
..          ...            ...
948           8              3
949          12              6
950           8              6
951          12              5
952          11              5

                                             cover_url
0                                            Not Found
1    https://i.scdn.co/image/ab67616d0000b2730656d5...
2    https://i.scdn.co/image/ab67616d0000b273e85259...
3    https://i.scdn.co/image/ab67616d0000b273e787cf...
4    https://i.scdn.co/image/ab67616d0000b273ab5c9c...
..                                                 ...
948  https://i.scdn.co/image/ab67616d0000b2730f5397...
949  https://i.scdn.co/image/ab67616d0000b273e0b60c...
950                                          Not Found
951                                          Not Found
952  https://i.scdn.co/image/ab67616d0000b273992a1f...

[953 rows x 25 columns]

In [10]:
data = data.drop(columns=["cover_url"])

In [11]:
data

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [14]:
data.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [15]:

data.columns = (
    data.columns
    .str.strip()            # remove leading/trailing spaces
    .str.lower()            # convert to lowercase
    .str.replace(" ", "_")  # replace spaces with underscores
    .str.replace(r"[^\w_]", "", regex=True)  # remove special characters
)

In [18]:
data.isnull().sum()

track_name               0
artists_name             0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_            0
valence_                 0
energy_                  0
acousticness_            0
instrumentalness_        0
liveness_                0
speechiness_             0
dtype: int64

In [19]:
data=data.dropna()

In [20]:
data.isnull().sum()

track_name              0
artists_name            0
artist_count            0
released_year           0
released_month          0
released_day            0
in_spotify_playlists    0
in_spotify_charts       0
streams                 0
in_apple_playlists      0
in_apple_charts         0
in_deezer_playlists     0
in_deezer_charts        0
in_shazam_charts        0
bpm                     0
key                     0
mode                    0
danceability_           0
valence_                0
energy_                 0
acousticness_           0
instrumentalness_       0
liveness_               0
speechiness_            0
dtype: int64

In [21]:
data

,track_name,artists_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_,valence_,energy_,acousticness_,instrumentalness_,liveness_,speechiness_
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

,track_name,artists_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_,valence_,energy_,acousticness_,instrumentalness_,liveness_,speechiness_
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [25]:
data = data.applymap(lambda x: x.lower() if isinstance(x, str) else x)

C:\Users\Sawpanil\AppData\Local\Temp\ipykernel_23532\396247792.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [32]:
import pandas as pd

# Loop through all object (string) columns
for col in data.select_dtypes(include="object").columns:
    data[col] = data[col].str.replace(r"[^\w_]", "", regex=True)

In [33]:
data

,track_name,artists_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_,valence_,energy_,acousticness_,instrumentalness_,liveness_,speechiness_
0,sevenfeatlattoexplicitver,lattojungkook,2,2023,7,14,553,147,141381703,43,...,125,b,major,80,89,83,31,0,8,4
1,lala,myketowers,1,2023,3,23,1474,48,133716286,48,...,92,c,major,71,61,74,7,0,10,4
2,vampire,oliviarodrigo,1,2023,6,30,1397,113,140003974,94,...,138,f,major,51,32,53,17,0,31,6
3,cruelsummer,taylorswift,1,2019,8,23,7858,100,800840817,116,...,170,a,major,55,58,72,11,0,11,15
4,whereshegoes,badbunny,1,2023,5,18,3133,50,303236322,84,...,144,a,minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,mymindme,selenagomez,1,2022,11,3,953,0,91473363,61,...,144,a,major,60,24,39,57,0,8,3
949,biggerthanthewholesky,taylorswift,1,2022,10,21,1180,0,121871870,4,...,166,f,major,42,7,24,83,1,12,6
950,avecesfeatfeid,feidpaulolondra,2,2022,11,3,573,0,73513683,2,...,92,c,major,80,81,67,4,0,8,6
951,enladeella,feidsechjhayco,3,2022,10,20,1320,0,133895612,29,...,97,c,major,82,67,77,8,0,12,5
952,alone,burnaboy,1,2022,11,4,782,2,96007391,27,...,90,e,minor,61,32,67,15,0,11,5

In [34]:
data

,track_name,artists_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_,valence_,energy_,acousticness_,instrumentalness_,liveness_,speechiness_
0,sevenfeatlattoexplicitver,lattojungkook,2,2023,7,14,553,147,141381703,43,...,125,b,major,80,89,83,31,0,8,4
1,lala,myketowers,1,2023,3,23,1474,48,133716286,48,...,92,c,major,71,61,74,7,0,10,4
2,vampire,oliviarodrigo,1,2023,6,30,1397,113,140003974,94,...,138,f,major,51,32,53,17,0,31,6
3,cruelsummer,taylorswift,1,2019,8,23,7858,100,800840817,116,...,170,a,major,55,58,72,11,0,11,15
4,whereshegoes,badbunny,1,2023,5,18,3133,50,303236322,84,...,144,a,minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,mymindme,selenagomez,1,2022,11,3,953,0,91473363,61,...,144,a,major,60,24,39,57,0,8,3
949,biggerthanthewholesky,taylorswift,1,2022,10,21,1180,0,121871870,4,...,166,f,major,42,7,24,83,1,12,6
950,avecesfeatfeid,feidpaulolondra,2,2022,11,3,573,0,73513683,2,...,92,c,major,80,81,67,4,0,8,6
951,enladeella,feidsechjhayco,3,2022,10,20,1320,0,133895612,29,...,97,c,major,82,67,77,8,0,12,5
952,alone,burnaboy,1,2022,11,4,782,2,96007391,27,...,90,e,minor,61,32,67,15,0,11,5

In [36]:
data.to_csv("spotify.csv",index=False)